"""Prompt Builder Service.

Constructs a structured prompt for the model combining enriched context,
column schema, and transcribed text for field extraction.
"""

from datetime import date

from app.models import ColumnSchema


class PromptBuilder:
    """Builds the extraction prompt for the OpenAI model."""

    def build(
        self,
        enriched_context: str,
        schema: ColumnSchema,
        transcribed_text: str,
        today: date | None = None,
        language: str = "es",
    ) -> str:
        """Construct the prompt for the model, in the given language.

        Includes:
        - Enriched context as system context
        - Schema table with name, data type, and example per column
        - Transcribed text as input to analyze
        - The current date, so a narrated date without a year resolves to the
          current year instead of a year the model invents (it has no clock)
        - JSON response format instructions

        Args:
            enriched_context: The enriched context generated by LLMEnrichmentService.
            schema: The column schema extracted from the Excel file.
            transcribed_text: The transcribed audio text to extract data from.
            today: Reference date used to resolve year-less dates. Defaults to the
                current date; injectable for deterministic tests.
            language: UI/record language ("es" or "en"); selects the prompt
                language. Defaults to Spanish.

        Returns:
            A formatted prompt string for the model.
        """
        today = today or date.today()
        # Schema table rows are language-independent (they hold the user's column
        # names, types, and examples verbatim).
        schema_rows = "\n".join(
            f"| {col.index} | {col.name} | {col.data_type} | {col.example_value} |"
            for col in schema.columns
        )

        if language == "en":
            return self._build_en(enriched_context, schema, schema_rows, transcribed_text, today)
        return self._build_es(enriched_context, schema, schema_rows, transcribed_text, today)

    def _build_es(self, enriched_context, schema, schema_rows, transcribed_text, today) -> str:
        json_example = ",\n  ".join(
            f'"{col.name}": "valor extraído"' for col in schema.columns
        )

        return (
            "Eres un asistente de extracción de datos. Tu tarea es identificar valores\n"
            "específicos en un texto transcrito de audio y retornarlos en formato JSON.\n\n"
            f"{enriched_context}\n\n"
            "---\n\n"
            "El esquema del Excel tiene las siguientes columnas:\n\n"
            "| # | Nombre | Tipo de dato | Ejemplo |\n"
            "|---|--------|--------------|---------|\n"
            f"{schema_rows}\n\n"
            "---\n\n"
            "Texto transcrito del audio:\n"
            f'"{transcribed_text}"\n\n'
            "---\n\n"
            "Instrucciones:\n"
            "- Identifica en el texto transcrito el valor correspondiente a CADA columna.\n"
            "- Distingue entre un dato que NO se menciona y un dato que se menciona como\n"
            "  ausente, inexistente o nulo:\n"
            '  - Si la columna no se menciona en el texto, usa un string vacío "".\n'
            "  - Si el texto indica explícitamente que algo no hay, no existe o es ninguno\n"
            '    (por ejemplo, "el lugar no cuenta con estacionamiento"), NO lo dejes vacío:\n'
            "    usa el valor que representa cero o ausencia según el tipo de dato\n"
            '    (0 para números, "no" para booleanos).\n'
            "- Respeta el tipo de dato indicado para cada columna.\n"
            f"- La fecha actual es {today:%d/%m/%Y}. Si en el texto se menciona una fecha\n"
            f"  sin año, usa el año actual ({today:%Y}); no uses ningún otro año por defecto.\n"
            "\n"
            "Ejemplos ilustrativos (muestran la diferencia entre un dato ausente y uno no\n"
            "mencionado; NO uses estos valores en tu respuesta):\n\n"
            "Ejemplo 1 — columnas: Lugar (texto), CanchasTenis (número entero),\n"
            "Fuentes (número entero), Horario (texto)\n"
            'Texto: "Visité el parque Central. No hay canchas de tenis. Tiene 3 fuentes."\n'
            'Respuesta: {"Lugar": "Central", "CanchasTenis": "0", "Fuentes": "3", "Horario": ""}\n'
            "(CanchasTenis es 0 porque el texto dice que NO hay; Horario queda vacío\n"
            "porque no se menciona.)\n\n"
            "Ejemplo 2 — columnas: Hotel (texto), Alberca (booleano)\n"
            'Texto: "El hotel Sol no cuenta con alberca."\n'
            'Respuesta: {"Hotel": "Sol", "Alberca": "no"}\n'
            '(Alberca es "no" porque el texto dice explícitamente que NO la tiene.)\n\n'
            "- Responde ÚNICAMENTE con un JSON válido con esta estructura exacta:\n"
            "{\n"
            f"  {json_example}\n"
            "}"
        )

    def _build_en(self, enriched_context, schema, schema_rows, transcribed_text, today) -> str:
        json_example = ",\n  ".join(
            f'"{col.name}": "extracted value"' for col in schema.columns
        )

        return (
            "You are a data-extraction assistant. Your task is to identify specific\n"
            "values in an audio transcription and return them in JSON format.\n\n"
            f"{enriched_context}\n\n"
            "---\n\n"
            "The Excel schema has the following columns:\n\n"
            "| # | Name | Data type | Example |\n"
            "|---|------|-----------|---------|\n"
            f"{schema_rows}\n\n"
            "---\n\n"
            "Audio transcription:\n"
            f'"{transcribed_text}"\n\n'
            "---\n\n"
            "Instructions:\n"
            "- Identify in the transcription the value that corresponds to EACH column.\n"
            "- Distinguish between a value that is NOT mentioned and one that is mentioned\n"
            "  as absent, non-existent, or none:\n"
            '  - If the column is not mentioned in the text, use an empty string "".\n'
            "  - If the text explicitly states that something does not exist or is none\n"
            '    (for example, "the place has no parking"), do NOT leave it empty:\n'
            "    use the value that represents zero or absence for the data type\n"
            '    (0 for numbers, "no" for booleans).\n'
            "- Respect the data type indicated for each column.\n"
            f"- The current date is {today:%Y-%m-%d}. If a date is mentioned without a\n"
            f"  year, use the current year ({today:%Y}); do not default to any other year.\n"
            "\n"
            "Illustrative examples (they show the difference between an absent value and\n"
            "an unmentioned one; do NOT use these values in your answer):\n\n"
            "Example 1 — columns: Place (text), TennisCourts (integer),\n"
            "Fountains (integer), Hours (text)\n"
            'Text: "I visited Central Park. There are no tennis courts. It has 3 fountains."\n'
            'Answer: {"Place": "Central", "TennisCourts": "0", "Fountains": "3", "Hours": ""}\n'
            "(TennisCourts is 0 because the text says there are NONE; Hours is empty\n"
            "because it is not mentioned.)\n\n"
            "Example 2 — columns: Hotel (text), Pool (boolean)\n"
            'Text: "The Sol hotel has no pool."\n'
            'Answer: {"Hotel": "Sol", "Pool": "no"}\n'
            '(Pool is "no" because the text explicitly says it does NOT have one.)\n\n'
            "- Respond ONLY with valid JSON in this exact structure:\n"
            "{\n"
            f"  {json_example}\n"
            "}"
        )
