"""Prompt Builder Service.

Constructs a structured prompt for the model combining enriched context,
column schema, and transcribed text for field extraction.
"""

from app.models import ColumnSchema


class PromptBuilder:
    """Builds the extraction prompt for the OpenAI model."""

    def build(
        self,
        enriched_context: str,
        schema: ColumnSchema,
        transcribed_text: str,
    ) -> str:
        """Construct the prompt for the model.

        Includes:
        - Enriched context as system context
        - Schema table with name, data type, and example per column
        - Transcribed text as input to analyze
        - JSON response format instructions

        Args:
            enriched_context: The enriched context generated by LLMEnrichmentService.
            schema: The column schema extracted from the Excel file.
            transcribed_text: The transcribed audio text to extract data from.

        Returns:
            A formatted prompt string for the model.
        """
        # Build schema table rows
        schema_rows = "\n".join(
            f"| {col.index} | {col.name} | {col.data_type} | {col.example_value} |"
            for col in schema.columns
        )

        # Build JSON structure example
        json_example = ",\n  ".join(
            f'"{col.name}": "valor extraído"' for col in schema.columns
        )

        return (
            "Eres un asistente de extracción de datos. Tu tarea es identificar valores\n"
            "específicos en un texto transcrito de audio y retornarlos en formato JSON.\n\n"
            f"{enriched_context}\n\n"
            "---\n\n"
            "El esquema del Excel tiene las siguientes columnas:\n\n"
            "| # | Nombre | Tipo de dato | Ejemplo |\n"
            "|---|--------|--------------|---------|\n"
            f"{schema_rows}\n\n"
            "---\n\n"
            "Texto transcrito del audio:\n"
            f'"{transcribed_text}"\n\n'
            "---\n\n"
            "Instrucciones:\n"
            "- Identifica en el texto transcrito el valor correspondiente a CADA columna.\n"
            "- Distingue entre un dato que NO se menciona y un dato que se menciona como\n"
            "  ausente, inexistente o nulo:\n"
            '  - Si la columna no se menciona en el texto, usa un string vacío "".\n'
            "  - Si el texto indica explícitamente que algo no hay, no existe o es ninguno\n"
            '    (por ejemplo, "el lugar no cuenta con estacionamiento"), NO lo dejes vacío:\n'
            "    usa el valor que representa cero o ausencia según el tipo de dato\n"
            '    (0 para números, "no" para booleanos).\n'
            "- Respeta el tipo de dato indicado para cada columna.\n"
            "\n"
            "Ejemplos ilustrativos (muestran la diferencia entre un dato ausente y uno no\n"
            "mencionado; NO uses estos valores en tu respuesta):\n\n"
            "Ejemplo 1 — columnas: Lugar (texto), CanchasTenis (número entero),\n"
            "Fuentes (número entero), Horario (texto)\n"
            'Texto: "Visité el parque Central. No hay canchas de tenis. Tiene 3 fuentes."\n'
            'Respuesta: {"Lugar": "Central", "CanchasTenis": "0", "Fuentes": "3", "Horario": ""}\n'
            "(CanchasTenis es 0 porque el texto dice que NO hay; Horario queda vacío\n"
            "porque no se menciona.)\n\n"
            "Ejemplo 2 — columnas: Hotel (texto), Alberca (booleano)\n"
            'Texto: "El hotel Sol no cuenta con alberca."\n'
            'Respuesta: {"Hotel": "Sol", "Alberca": "no"}\n'
            '(Alberca es "no" porque el texto dice explícitamente que NO la tiene.)\n\n'
            "- Responde ÚNICAMENTE con un JSON válido con esta estructura exacta:\n"
            "{\n"
            f"  {json_example}\n"
            "}"
        )
