"""Prompt Builder Service.

Constructs a structured prompt for Claude combining enriched context,
column schema, and transcribed text for field extraction.
"""

from app.models import ColumnSchema


class PromptBuilder:
    """Builds the extraction prompt for Claude API."""

    def build(
        self,
        enriched_context: str,
        schema: ColumnSchema,
        transcribed_text: str,
    ) -> str:
        """Construct the prompt for Claude.

        Includes:
        - Enriched context as system context
        - Schema table with name, data type, and example per column
        - Transcribed text as input to analyze
        - JSON response format instructions

        Args:
            enriched_context: The enriched context generated by LLMEnrichmentService.
            schema: The column schema extracted from the Excel file.
            transcribed_text: The transcribed audio text to extract data from.

        Returns:
            A formatted prompt string for Claude.
        """
        # Build schema table rows
        schema_rows = "\n".join(
            f"| {col.index} | {col.name} | {col.data_type} | {col.example_value} |"
            for col in schema.columns
        )

        # Build JSON structure example
        json_example = ",\n  ".join(
            f'"{col.name}": "valor extraído"' for col in schema.columns
        )

        return (
            "Eres un asistente de extracción de datos. Tu tarea es identificar valores\n"
            "específicos en un texto transcrito de audio y retornarlos en formato JSON.\n\n"
            f"{enriched_context}\n\n"
            "---\n\n"
            "El esquema del Excel tiene las siguientes columnas:\n\n"
            "| # | Nombre | Tipo de dato | Ejemplo |\n"
            "|---|--------|--------------|---------|\n"
            f"{schema_rows}\n\n"
            "---\n\n"
            "Texto transcrito del audio:\n"
            f'"{transcribed_text}"\n\n'
            "---\n\n"
            "Instrucciones:\n"
            "- Identifica en el texto transcrito el valor correspondiente a CADA columna.\n"
            '- Si no puedes identificar un valor para alguna columna, usa un string vacío "".\n'
            "- Respeta el tipo de dato indicado para cada columna.\n"
            "- Responde ÚNICAMENTE con un JSON válido con esta estructura exacta:\n"
            "{\n"
            f"  {json_example}\n"
            "}"
        )
